# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LYCTplSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit', '~> 4.2.0'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'ObjectMapper', '~> 3.4.1'
  
  pod 'PagingMenuController', '~> 2.2.0'
  
  # Pods for LYCTplSwift

  target 'LYCTplSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYCTplSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
